import {IssueTypes} from "../../types";

const issue = {
    regexOrAST: 'Regex',
    type: IssueTypes.L,
    title: 'PUSH0 is not supported by all chains',
    description: 'Solc compiler version 0.8.20 switches the default target EVM version to Shanghai, which means that the generated bytecode will include PUSH0 opcodes. Be sure to select the appropriate EVM version in case you intend to deploy on a chain other than mainnet like L2 chains that may not support PUSH0, otherwise deployment of your contracts will fail.',
    regex: /pragma solidity\s*((\^0\.[1-7]\.\d+)|(\^0\.8\.(1[0-9]|0?\d))|(~>0\.[1-7]\.\d+)|(~>0\.8\.(1[0-9]|0?\d))|(>=0\.8\.[0-9]+ <0\.8\.20)|(0\.[1-7]\.\d+))/g
};

export default issue;
